### ISSUE TITLE
file should contain at least 2 and max 4 users

### ISSUE THREAD

**Issue by mudi256** [ConnectyCube/connectycube-android-samples#13]
The user_config.json file should contain at least 2 and max 4 users with format ["login":"password"]

**Comment by CubeRomanMagellan** [comment]
Hello @mudi256, yes, here is example of user_config.json:
`{`
 `"user_1_login": "user_1_password",`
  `"user_2_login": "user_2_password",`
 `"user_3_login": "user_3_password",`
  `"user_4_login": "user_4_password"`
`}`

**Comment by mudi256** [comment]
where from the users came in "user_config.json"
i add below users in "user_config.json" but when i run the app all disappear
"user_1_login": "user_1_password",
"user_2_login": "user_2_password",
"user_3_login": "user_3_password",
"user_4_login": "user_4_password"

**Comment by mudi256** [comment]
and in my connectycube dashboard having 2 users

**Comment by CubeRomanMagellan** [comment]
Those "user_1_login": "user_1_password" etc., are an example. You need just add your users logins and passwords to "user_config.json".

**Comment by gabriel-TheCode** [comment]
Close this issue please
